import type { AppProps } from 'next/app';
import Head from 'next/head'
import { Header } from '../components/Header';
import { Footer } from '../components/Footer';

import 'bootstrap/dist/css/bootstrap.min.css';
import '../styles/globals.css'
import store from '../store';
import React from 'react';
import { Provider } from 'react-redux';

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <Provider store={store}> 
      <Head>
        <title>Shortly</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/favicon-32x32.png" />
      </Head>

      <Header/>
      <Component {...pageProps} /> 
      <Footer/>
    </Provider>
  ); 
}

export default MyApp
